apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: inntekt
  namespace: aap
  labels:
    team: aap
    sub: vedtak
spec:
  image: {{image}}
  replicas:
    cpuThresholdPercentage: 90
    disableAutoScaling: true
    max: 1
    min: 1
  azure:
    application:
      enabled: true
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  kafka:
    pool: {{kafka-pool}}
    streams: true
  liveness:
    path: /actuator/live
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/ready
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  prometheus:
    enabled: true
    path: /actuator/metrics
  secureLogs:
    enabled: true

  env:
    - name: PROXY_BASE_URL
      value: https://aap-fss-proxy.dev-fss-pub.nais.io
    - name: PROXY_SCOPE
      value: "api://dev-fss.aap.fss-proxy/.default"
    - name: POPP_BASE_URL
      value: https://pensjon-popp-q2.dev-fss-pub.nais.io/popp/api
    - name: POPP_SCOPE
      value: "api://dev-fss.pensjonopptjening.pensjon-popp-q2/.default"
