apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: inntekt
  namespace: aap
  labels:
    team: aap
spec:
  image: {{image}}
  replicas:
    cpuThresholdPercentage: 90
    disableAutoScaling: true
    max: 1
    min: 1
  resources:
    limits:
      cpu: 1000m
      memory: 8Gi
    requests:
      cpu: 500m
      memory: 4Gi
  kafka:
    pool: {{kafka-pool}}
    streams: true
  liveness:
    path: /actuator/healthy
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  readiness:
    path: /actuator/healthy
    initialDelay: 3
    periodSeconds: 3
    failureThreshold: 21
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true

  env:
    - name: LOG_APPENDER
      value: json