on: [ pull_request ]
name: Pull Request

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'temurin'

      - uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: test --continue --no-daemon --configuration-cache

      - uses: dorny/test-reporter@v1.6.0
        if: success() || failure()
        with:
          name: test
          path: "**/build/test-results/test/TEST-*.xml"
          reporter: java-junit
          token: ${{ secrets.GITHUB_TOKEN }}
